### ISSUE TITLE
旧版正方教务系统课程表插件索取

### ISSUE THREAD

**Issue by Hydsiun** [31415926535x/CollegeProjectBackup#1]
您好！
       在使用您的插件中我意识到我校正方仍为旧版正方系统，导致贵插件并不能使用，看了介绍想索要一下旧版正方插件，可否发于邮箱：a1123410989@gmail.com ?谢谢，祝您一切都好。

**Comment by 31415926535x** [comment]
https://github.com/31415926535x/CollegeProjectBackup/blob/master/ZhengfangClassScheduleToICS/ZhengFangClassScheduleToICS_OLD.js 这个就是旧版的插件，是另一个大佬写的，（不知道能不能使用，当时我使用的时候有一些小问题，就想着自己写一个，然后就拖到了学校换新版教务系统了，，2333，，不能用的话就自己稍微改一改吧，，）
