### ISSUE TITLE
编译原理实验四注释问题

### ISSUE THREAD

**Issue by rumosky** [31415926535x/CollegeProjectBackup#2]
路径CollegeProjectBackup/ExperimentalReport/ComplierPrinciple/Experiment_4_SemanticAnalysisAndIntermediateCodeGeneration/program/symbols.h

这个文件的第24行，`设置place`应该是注释，否则会出错

**Comment by 31415926535x** [comment]
这个，，可能和编译器什么有关系吧，，
我这里是可以正常编译运行的，，不过在学校的评测姬上就不能编译，，，所以我就把这些文件合并提交的是 ``SemanticAnalysisAndIntermediateCodeGeneration.cpp`` 这个文件，，你看着改一下能运行就行了，，😄，，

（实际上我这种 ``#include"xxx.cpp"`` 写法也是不标准的，，但是本地的编译器和vscode不知道怎么不认  ``#include"xxx.h"`` 所以就使用了这种投机技巧，，XD

**Comment by rumosky** [comment]
> 这个，，可能和编译器什么有关系吧，，
> 我这里是可以正常编译运行的，，不过在学校的评测姬上就不能编译，，，所以我就把这些文件合并提交的是 ``SemanticAnalysisAndIntermediateCodeGeneration.cpp`` 这个文件，，你看着改一下能运行就行了，，😄，，
> 
> （实际上我这种 ``#include"xxx.cpp"`` 写法也是不标准的，，但是本地的编译器和vscode不知道怎么不认  ``#include"xxx.h"`` 所以就使用了这种投机技巧，，XD

那确实应该是编译器的关系。我早改好了，可以运行。

**Comment by 31415926535x** [comment]
😄XD
