### ISSUE TITLE
bug:由该脚本导出的ics课程表中的调课课程课程名信息丢失

### ISSUE THREAD

**Issue by sdy623** [31415926535x/CollegeProjectBackup#8]
如图:像这样的调课课程，在我打开ics文件后发现课程名丢失
![image.png](https://i.loli.net/2021/02/25/iQc9Wy6nUHVjZEz.png)
![image.png](https://i.loli.net/2021/02/25/r2ExIm7i4FkJBHh.png)
查看html标签，发现调课课程名的html标签发生了改变。
原本的标签：
`<span class="title"><font color="blue">下北泽☆</font></span>`
调课标签：
`<u class="title showJxbtkjl" data-jxb_id="B3F4B1D04B0F9DF4E053868F45D3150C" style="cursor: pointer;"><font color="blue">【调】先辈☆</font></u>`

**Comment by 31415926535x** [comment]
已经尝试修复了，你看看现在如何。。。
