### ISSUE TITLE
[Bug] 课程名称均漏了最后一个字符，当有【调】标注的课程课程名称错乱

### ISSUE THREAD

**Issue by cxy5014** [31415926535x/CollegeProjectBackup#9]
如题。

**Comment by 31415926535x** [comment]
emmm貌似我这里有【调】的课程也没有问题啊，，
我是直接获取的课程的名字，没有进行截断处理

你要不发个截图：F12打开控制台，运行脚本，然后点开course那个三角，显示出所获取的课程信息，
大概类似这样。。
![image](https://user-images.githubusercontent.com/16176071/116080151-48824180-a6cb-11eb-91b9-3e1bf252abcf.png)

**Comment by cxy5014** [comment]
这个是有关截图。
![Screen Shot 2021-04-26 at 20 12 36](https://user-images.githubusercontent.com/42842481/116080624-e6760c00-a6cb-11eb-88b8-43a44260f94f.png)

**Comment by 31415926535x** [comment]
我修改了一下，你有时间看看现在是否可以使用了呢；
（可能你那边的第一个课程会获取到很长一段，，，，
（其次我把那个不好看的【调】去掉了😂

**Comment by cxy5014** [comment]
现在可以正常使用了。谢谢！

**Comment by 31415926535x** [comment]
没事没事QAQ😀
